input EntityDefinitionInput {
    """
    NB: This can be different from the `id` argument passed to updateEntityDefinition(), in the case
    where the user changes the ID
    """
    id: ID!
    label: String
    # displayNameTemplate: String
    pluralLabel: String!
    description: String
    templateEntityDefinitionId: ID
    isAbstract: Boolean! = false
    # hasUrl: Boolean!
    #
    # If we support fieldsets in the future, then this field will probably no longer be needed.
    # `properites` is optional so that you can update just the basic attributes of an entity definition
    # without re-sending all the properties.
    properties: [PropertyInput!]
    # fieldsets: [PropertyFieldsetInput!]
}

# input PropertyFieldsetInput {
#     title: String
#     properties: [PropertyInput!]
#     computedProperties: [ComputedPropertyInput!]
# }

input PropertyInput {
    id: String!
    label: String!
    dataType: String!
    readOnly: Boolean!
    # editingComponent: String!
    # TODO
    # flags: [PropertyFlagInput!]

    # Separate fields for different sub-types of Property, since graphql does not currently support
    # polymorphic input types (i.e. unions/interfaces)
    # literalProperty: LiteralPropertyInput
    # associationProperty: AssociationDefinitionInput
    # staticAssetProperty: StaticAssetPropertyInput
}

# input LiteralPropertyInput {
#     # defaultValue: LiteralPropertyValueScalar
# }

type Mutation {
    createEntityDefinition(
        entityDef: EntityDefinitionInput!
    ): EntityDefinitionModerationStatus

    updateEntityDefinition(
        id: ID!
        entityDef: EntityDefinitionInput!
    ): EntityDefinitionModerationStatus
}
