type Query {
    entityDefinitions: EntityDefinitionResults!
    entityDefinition(id: ID!): EntityDefinition
    entities(where: EntityFilters!): EntityResults!
    entity(entityDefId: ID!, entityId: ID!): Entity
}
